### ISSUE TITLE
Rift Mage portality

### ISSUE THREAD

**Issue by PenginKami** [QuantumXenon/origins-plus-plus#267] opened 2023-09-09 03:18 UTC
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric

**Versions**
- Minecraft Version 1.20.1
- Mod Loader Version - 0.14.22
- Origins Version 1.20.1-1.10.0
- Origins++ Version 2.1.2
- Pehkui Version 3.78+1.14.4-1.20.1

**Origin**
Rift Mage

**Power**
Portality

Something to do with either/both unloading chunks and changing dimensions via commands can allow you to place multiple rifts near eachother when you should only be able to place one overall.

**Notes**
This is on a server, might be fixable by having the server remember where rifts are in a folder or smthing /shrug I don't know coding. 

Completely separate - But wanted to ask anyway:

having a config in the server for bedrockean items obtainable from the treasure ability would be nice, as well as even blacklisting/whitelisting certain blocks for modded compatibility. 

pss whens the next update planned to be out, cause I really wanna update my server ;)

**Comment by QuantumXenon** [comment] 2023-09-09 10:51
Due to the nature of Origins++ (a datapack packaged as a mod), it would not be easy to have a config file for obtainable items, though a new tag could be made to add items to that could be found which could be added to with another datapack

I plant to release the update in the next couple of weeks.

**Comment by QuantumXenon** [comment] 2023-09-10 20:32
Also, any block in `origins:natural_stone`  has a chance to drop the items for the Bedrockean.

**Comment by QuantumXenon** [comment] 2023-09-18 11:23
I also haven't been able to reproduce the issue with the rift cooldown not working across dimensions. As I have discussed all reported points, I will close the issue.

As for the update, it should be released in the next few days.

**Closed by QuantumXenon** 2023-09-18 11:23 UTC
Labels: bug
