### ISSUE TITLE
A Very Strange Bug That Only Occurs Sometimes When Joining a Pre-Made World

### ISSUE THREAD

**Issue by joemama098463** [QuantumXenon/origins-plus-plus#125] opened 2023-01-01 00:02 UTC
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Forge 43.2
- Origins Version 1.5.0.6
- Origins++ Version 1.7.2
- Pehkui Version 3.6.1

Okay so, I've been testing this out for a while now, tried it with tons of other mods and standalone with needed dependencies, but for whatever reason, at complete random things will just fail to load. Sometimes it'll be small, a missing power or missing ability key or a wrong description, but other times it'll be massive, like corruption of entire worlds before they're even played for the first time, failing to load the ENTIRE A.Po.Li. library, and sometimes everything goes perfectly fine. Because of the nature of this bug I can't easily verify much about it, but it seems most common when joining an already existing world and least common when creating one. I have positively no idea what spurs on the bug nor why it happens because I keep getting different results each time I join a world.

**Comment by QuantumXenon** [comment] 2023-01-01 00:35
I'm not certain, but this is probably a bug with Origins (Forge) itself.

**Comment by joemama098463** [comment] 2023-01-01 02:19
ah, I see, will keep this updated just in case it ain't tho

Addendum 1:
-did some more testing, it appears to have something to do with the way Minecraft saves data, as sometimes when removing mods the issue is temporarily fixed
-may be a conflict with the "Everlasting Abilities" and "Cyclops Core" mods leaving an imprint on this data saving code, these seem to have the most impact regarding the bug

**Comment by joemama098463** [comment] 2023-01-02 00:01
further testing has revealed it to indeed be a conflict between this mod and everlasting abilities

**Comment by miniscule-minecrafter** [comment] 2023-01-02 04:09
I've also been experiencing this issue with similar versions and the same loader. I even tried Origins++ and regular Origins among a few other supporting mods to determine if it was from another source, but Origins++ seems to mainly be the issue.

I've been messing around with single player worlds to test the bugs and even looked around the configs (I'm not the most proficient with that stuff though, so I didn't see any noticeable issues). The problem started whenever I created a new world; I could enter and use the mod as normal, but as soon as I left and attempted to rejoin it would hit me with "Invalid Player Data".

I tried a few more times to determine the consistency of the problem and realized the response was a little different each time
(A few examples):
* Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129921_()" because "server" is null
* Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root/apoli:configured_power] was missing.

Sometimes I couldn't even get passed the creation of a single player world and the whole game crashed (the first example above). Not sure what's happening, but I've been trying to figure it out for four hours now. Whole thing has me stumped.

**Comment by joemama098463** [comment] 2023-01-03 03:13
for the invalid player data thing you need the resource pack mod... thing linked in "solutions to frequent issues"

**Comment by joemama098463** [comment] 2023-01-04 22:26
update #3: problem has resurfaced

**Comment by QuantumXenon** [comment] 2023-01-04 22:41
> update #3: problem has resurfaced

More specifically, from what I have experienced, it seems to be a bug with how Origins (Forge) handles addons

**Comment by QuantumXenon** [comment] 2023-01-13 16:52
I've added this to #112, but I don't know what I can do to help resolve this issue except for reporting the bug to the Origins (Forge) developer

**Comment by QuantumXenon** [comment] 2023-01-25 18:11
@miniscule-minecrafter @joemama098463 I'm going to close this issue as it I'm almost certain it's caused by an issue with the way Origins (Forge) handles addons, potentially because Origins++ is very large. There isn't much I can do about it, but the next version will be ~15% smaller in file size (due to internal improvements) which might help a bit.

**Closed by QuantumXenon** 2023-01-25 18:11 UTC
Labels: bug, forge issue?
