### ISSUE TITLE
Forge Version Breaks Server

### ISSUE THREAD

**Issue by Solar-Dolphin** [QuantumXenon/origins-plus-plus#17] opened 2022-05-08 21:22 UTC
hey okay I am having an issue i put this mod on my private server and downloaded it to my modpack but it wont let me join the server (it is a forge server and pack.) 

this is the exact console error given when i join the server

[20:57:33] [User Authenticator #1/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player Solar_DolphinYT is 58714e32-ad74-4790-80f5-72119ffea12a
[20:57:34] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@72e55323[id=58714e32-ad74-4790-80f5-72119ffea12a,name=Solar_DolphinYT,properties={textures=[com.mojang.authlib.properties.Property@470e598d]},legacy=false] (/158.62.161.105:61909) lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 3471464 into 3

**Comment by QuantumXenon** [comment] 2022-05-08 22:11
Try installing this: https://www.curseforge.com/minecraft/mc-mods/xl-packets

**Comment by Solar-Dolphin** [comment] 2022-05-08 23:03
it is a 1.18.2 server and i can join a single player world

**Comment by QuantumXenon** [comment] 2022-05-08 23:51
Sorry, I didn’t check that mod to see if it was available for 1.18. 

According to https://board.aternos.org/thread/7863-cant-join-cant-fit-number-into-3/, the error might have something to do with very large scoreboards.

To make it easier to try and find a problem, please answer the following: 

> Is it a new single player world?
> Have you isolated my mod to be the issue? 
> What other mods are you using?

**Comment by Solar-Dolphin** [comment] 2022-05-09 05:01
Yes i have isolated the mod to be the issue as it is the only one added before the issue started. 
there is no crash log as the server does not crash it just keeps the player from joining.
and i am using the darkRPG forge rpg quest magic dark souls 1.18.2 modpack on curse forge.




Full Mod list:
[TFB][1.18.1+Forge}Anthro_Origins_v1.4.jar
95.37 kB
May 3rd, 2022 4:54PM
AdvancementPlaques-1.18.1-1.4.2.jar
199.91 kB
May 3rd, 2022 4:54PM
AgeOfWeapons-Reforged-1.18.2-(v.0.3.2).jar
1.14 MB
May 3rd, 2022 4:54PM
AI-Improvements-1.18-0.4.0.jar
24.73 kB
May 3rd, 2022 4:54PM
alexsmobs-1.17.5.jar
20.94 MB
May 3rd, 2022 4:54PM
architectury-4.2.50.jar
502.24 kB
May 3rd, 2022 4:54PM
awesomedungeon-2.0.8.jar
351.19 kB
May 3rd, 2022 4:54PM
AwesomeDungeonEnd-Forge-1.18.2-1.0.1.jar
153.88 kB
May 3rd, 2022 4:54PM
AwesomeDungeonNether-Forge-1.18.2-1.0.1.jar
186.04 kB
May 3rd, 2022 4:54PM
AwesomeDungeonOcean-Forge-1.18.2-2.0.5.jar
157.23 kB
May 3rd, 2022 4:54PM
BetterAdvancements-1.18.2-0.2.0.129.jar
69.21 kB
May 3rd, 2022 4:54PM
betterfpsdist-1.18.2-1.5.jar
16.06 kB
May 3rd, 2022 4:54PM
BetterThirdPerson-Forge-1.18.2-1.7.3.jar
46.86 kB
May 3rd, 2022 4:54PM
bonsaitrees3-3.1.0.jar
305.4 kB
May 3rd, 2022 4:54PM
Bookshelf-Forge-1.18.2-13.0.13.jar
195.58 kB
May 3rd, 2022 4:54PM
brutalbosses-1.18.2-4.4.jar
162.61 kB
May 3rd, 2022 4:54PM
bucolicorigins-3.1[FORGE].jar
226.55 kB
1 day ago
caelus-forge-1.18.1-3.0.0.2.jar
36.29 kB
May 3rd, 2022 4:54PM
chat_heads-0.6.0-forge-1.18.1.jar
26.81 kB
May 3rd, 2022 4:54PM
cherishedworlds-forge-1.18-5.1.1.0.jar
47.23 kB
May 3rd, 2022 4:54PM
Chunky-1.2.164.jar
237.73 kB
May 3rd, 2022 4:54PM
citadel-1.11.2-1.18.2.jar
492.21 kB
May 3rd, 2022 4:54PM
clickadv-1.18.2-2.5.jar
14.91 kB
May 3rd, 2022 4:54PM
cloth-config-6.2.57-forge.jar
1.08 MB
May 3rd, 2022 4:54PM
Clumps-forge-1.18.2-8.0.0+8.jar
9.97 kB
May 3rd, 2022 4:54PM
collective-1.18.2-4.25.jar
142.05 kB
May 3rd, 2022 4:54PM
configured-1.5.3-1.18.2.jar
135.96 kB
May 3rd, 2022 4:54PM
Controlling-forge-1.18.2-9.0+19.jar
113.67 kB
May 3rd, 2022 4:54PM
curios-forge-1.18.2-5.0.7.0.jar
264.33 kB
May 3rd, 2022 4:54PM
drippyloadingscreen_forge_1.5.1_MC_1.18-1.18.1.jar
317.8 kB
May 3rd, 2022 4:54PM
DungeonCrawl-1.18.2-2.3.7.jar
751.04 kB
May 3rd, 2022 4:54PM
DungeonsArise-1.18.2-2.1.50c-beta.jar
5.16 MB
May 3rd, 2022 4:54PM
EnchantmentDescriptions-Forge-1.18.2-10.0.2.jar
55.05 kB
May 3rd, 2022 4:54PM
EpicFight-18.0.3-beta.jar
3.78 MB
May 3rd, 2022 4:54PM
ferritecore-4.2.0-forge.jar
104.16 kB
May 3rd, 2022 4:54PM
firstjoinmessage_1.18.2-1.4.jar
7.58 kB
May 3rd, 2022 4:54PM
FpsReducer2-forge-1.18.2-2.0.jar
112.73 kB
May 3rd, 2022 4:54PM
ftb-chunks-forge-1802.3.5-build.130.jar
720.51 kB
May 3rd, 2022 4:54PM
ftb-library-forge-1802.3.6-build.115.jar
557.26 kB
May 3rd, 2022 4:54PM
ftb-quests-forge-1802.3.8-build.101.jar
922.3 kB
May 3rd, 2022 4:54PM
ftb-teams-forge-1802.2.6-build.51.jar
164.47 kB
May 3rd, 2022 4:54PM
GameMenuModOption-1.18-Forge-1.14.jar
92.49 kB
May 3rd, 2022 4:54PM
geckolib-1.18-forge-3.0.15.jar
2.72 MB
May 3rd, 2022 4:54PM
Highlighter-1.18.1-1.1.2.jar
24.22 kB
May 3rd, 2022 4:54PM
horsestandstill-1.18-1.0.2.jar
10.89 kB
May 3rd, 2022 4:54PM
humancompanions-1.18.2-1.4.4.jar
290 kB
May 3rd, 2022 4:54PM
Iceberg-1.18.2-1.0.40.jar
89.28 kB
May 3rd, 2022 4:54PM
ImprovedMountHUD-v3.1.0-1.18.2-Forge.jar
59.72 kB
May 3rd, 2022 4:54PM
InventoryHud_[1.18].forge-3.4.4.jar
196.36 kB
May 3rd, 2022 4:54PM
item-filters-forge-1802.2.7-build.21.jar
105.29 kB
May 3rd, 2022 4:54PM
ItemBorders-1.18.1-1.1.5.jar
17.26 kB
May 3rd, 2022 4:54PM
jei-1.18.2-9.5.5.174.jar
938.03 kB
May 3rd, 2022 4:54PM
justzoom_forge_1.0.1_MC_1.18-1.18.1.jar
7.45 kB
May 3rd, 2022 4:54PM
konkrete_forge_1.3.3_MC_1.18-1.18.1.jar
192.64 kB
May 3rd, 2022 4:54PM
libnonymous-2.1.0.jar
292.89 kB
May 3rd, 2022 4:54PM
LibraryFerret-Forge-1.18.2-1.0.3.jar
7.22 kB
May 3rd, 2022 4:54PM
lobby_1.18.2-3.0.0.jar
511.75 kB
May 3rd, 2022 4:54PM
meetyourfight-1.18.2-1.2.4.jar
1.92 MB
May 3rd, 2022 4:54PM
minecraft-comes-alive-7.2.1+1.18.2-forge.jar
5.02 MB
May 3rd, 2022 4:54PM
origins_plus_plus-[FORGE]-1.5.1 (1).jar
974.32 kB
about 8 hours ago
Origins-1.18.2-1.4.1.1-unified.jar
1.72 MB
May 3rd, 2022 4:54PM
origins-classes-forge-1.1.2.jar
164.41 kB
May 3rd, 2022 4:54PM
passiveshield_1.18.2-2.0.jar
8.81 kB
May 3rd, 2022 4:54PM
Pehkui-3.3.0+1.18.2-forge (1).jar
326.12 kB
about 8 hours ago
polymorph-forge-1.18.1-0.43.jar
247.68 kB
May 3rd, 2022 4:54PM
PuzzlesLib-v3.3.2-1.18.2-Forge.jar
122.27 kB
May 3rd, 2022 4:54PM
randomtp-6.1.0+1.18-forge.jar
1.09 MB
May 3rd, 2022 4:54PM
shutupexperimentalsettings-1.0.5.jar
4.64 kB
May 3rd, 2022 4:54PM
sophisticatedbackpacks-1.18.2-3.15.17.559.jar
1.46 MB
May 3rd, 2022 4:54PM
stalwart-dungeons-1.18.2-1.2.2.jar
1.22 MB
May 3rd, 2022 4:54PM
starlight-1.0.2+forge.546ae87.jar
108 kB
May 3rd, 2022 4:54PM
starterkit_1.18.2-3.2.jar
14.4 kB
May 3rd, 2022 4:54PM
theoneprobe-1.18-5.1.0.jar
322.07 kB
May 3rd, 2022 4:54PM
welcomemessage_1.18.2-1.1.jar
8.9 kB
May 3rd, 2022 4:54PM
worldborder_1.18.2-2.6.jar
11.67 kB
May 3rd, 2022 4:54PM
worldedit-mod-7.2.10.jar

(copy and pasted from the server files)

**Comment by QuantumXenon** [comment] 2022-05-09 09:50
Ok, I’m going to guess the issue is due to packet sizes being too big (because of all the mods adding stuff that needs to be transferred to the client). The mod I sent before should fix this, but it isn’t available for 1.18. In the meantime, I’ll see if I can find another mod to fix this issue. My mod adds a lot of stuff to be sent to the client (as all the origins will be transferred), so it might be too much for the default packet limit.

**Comment by QuantumXenon** [comment] 2022-05-09 16:11
Can you export the modpack and send it to me on here? I would like to try something that might fix it.

**Comment by QuantumXenon** [comment] 2022-05-09 16:13
I'm working on a potential fix

**Comment by EnderDaddy** [comment] 2022-05-09 21:38
You rock Quantum. I just came here to report this. I also isolated to only happening with Origins++. (XP Packets and Bigger Packets Please don't alleviate the issue.) Let us know if you need more information. Good luck friend!

**Comment by QuantumXenon** [comment] 2022-05-09 21:55
@EnderDaddy Is that due to them being for the wrong Minecraft version?

(Because I'm working on forking XL Packets to 1.18.2)

**Comment by EnderDaddy** [comment] 2022-05-10 01:47
I sure hope so! I also messed around with Bucolic Origins a bit (https://www.curseforge.com/minecraft/mc-mods/bucolic-origins/files/3709040) and it has a similar problem. It can't handle the packet sizes between the client and the server. Both (origins+= and Bucolic) work fine in singleplayer, but crash with the aforementioned packet error every time they try to connect to a server.

**Comment by Solar-Dolphin** [comment] 2022-05-10 02:58
Bucolic origins seems to work fine on my server it was what i put in after the first time that Origins + + failed

**Comment by EnderDaddy** [comment] 2022-05-10 03:27
I did manage to get Bucolic to work. Here's some more information for you Quantum.... Not sure how helpful it is or no....


[09.05 22:24:26] [Server] [Netty Epoll Server IO #3/WARN] [co.co.Connectivity/]: Login payload for CALIO-S2CLoginDynamicRegistriesPacket is using 277.8446% of max allowed vanilla size and will cause errors during login if connectivity is not present on client side.
[09.05 22:24:26] [Server] [Netty Epoll Server IO #3/WARN] [co.co.Connectivity/]: Login payload for Registry minecraft:item is using 27.0237% of max allowed vanilla size
[09.05 22:24:26] [Server] [User Authenticator #1/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player EnderDaddy404 is 3bdcdb38-ea77-4643-b70c-ad986e3e91a2
[09.05 22:24:26] [Disconnect] (/73.94.78.12:52206) has disconnected, reasonInternal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2913449 into 3

**Comment by QuantumXenon** [comment] 2022-05-10 22:44
I’m doing by best to resolve the issue, but I not having any luck. I’ll keep this issue updated with anything I find

**Comment by EnderDaddy** [comment] 2022-05-11 01:47
> Bucolic origins seems to work fine on my server it was what i put in after the first time that Origins + + failed

Hey @Solar-Dolphin , if you add Connectivity mod ( https://www.curseforge.com/minecraft/mc-mods/connectivity) to your modpack, are you able to get Origins++ to work?

**Comment by QuantumXenon** [comment] 2022-05-11 06:37
> if you add Connectivity mod ( https://www.curseforge.com/minecraft/mc-mods/connectivity) to your modpack, are you able to get Origins++ to work?

I found the same modpack that Solar-Dolphin is using, and it tried Connectivity, but it didn’t work

**Comment by EnderDaddy** [comment] 2022-05-12 19:00
What if you only put 50 mods in (instead of 110+) would that allow it to work? (I don't quite understand the difficulty of what I'm asking, so I apologize if that's a dumb question.)

**Comment by QuantumXenon** [comment] 2022-05-12 21:25
> What if you only put 50 mods in (instead of 110+) would that allow it to work? (I don't quite understand the difficulty of what I'm asking, so I apologize if that's a dumb question.)

I tried with just the mod on its own, and there was still a problem, so I need to figure out why it isn't working. I have asked in some forums, but I haven't had a response yet

**Comment by QuantumXenon** [comment] 2022-05-18 19:11
> 
It’s a datapack that registers itself as a mod (so there is no coding).

**Comment by QuantumXenon** [comment] 2022-05-20 18:36
| @EnderDaddy @Solar-Dolphin | I have been in contact with the developer for Origins (Forge) and they said that they were aware of this issue, however they are not actively working on the mod (due to college related things). This would lead me to believe that there is an issue with loading origins from external mods (however I might be mistaken). My mod contains a very large number of origins, which could be why it breaks on servers

**Comment by EnderDaddy** [comment] 2022-05-20 18:57
@QuantumXenon That makes a lot of sense actually... Hmm... I'm trying to decide if I should work on the Origins mod or work on your "plus plus" datapack/mod.... I'm a developer by trade and want to get into Minecraft modding... I think that if we drop the number of mods on your datapack, we can get it to work for everyone.... Thoughts?

**Comment by QuantumXenon** [comment] 2022-05-20 20:42
@EnderDaddy If you want to code, then mine is not a good start (as it only has code to register itself)

Downsizing the number of origins in the datapack might fix the issue until a permanent solution is found. You are welcome to try this if you want, and if not, I'll get around to it.

**Comment by Hagura71** [comment] 2022-05-24 23:06
@QuantumXenon I was just wondering if the issue was fixed in the latest patch.

**Comment by QuantumXenon** [comment] 2022-05-24 23:14
@Hagura71 No, I haven’t been able to solve it yet

**Comment by EnderDaddy** [comment] 2022-05-24 23:38
I’m doing some work on it too @QuantumXenon. To help solve it. I’m just trying to wrap my head around how datapacks work. Little different than the typical dev work I do…

**Comment by chloooooooooooo** [comment] 2022-06-02 10:43
has anyone got it to work please? my friends really wanna use it

**Closed** 2022-06-23 16:27 UTC
Labels: other, need help

**Comment by QuantumXenon** [comment] 2022-06-23 16:35
| @EnderDaddy @Hagura71 @Solar-Dolphin @chloooooooooooo | This issue has now been fixed, so will be releasing an updates very soon. Huge thanks to the Origins (Forge) developer (https://github.com/EdwinMindcraft) for helping me to fix the issue.

**Comment by CamoNinja** [comment] 2022-06-23 16:55
Dude @QuantumXenon you rock!!! Way to go friend! Proud of you for not giving up! :)

**Comment by EnderDaddy** [comment] 2022-06-23 16:58
Dude @QuantumXenon you rock!!! Way to go! Proud of you for getting this figured out! Way to not give up! :) KUDOS!!
