### ISSUE TITLE
World Making - Invalid Player Data

### ISSUE THREAD

**Issue by Tox-y** [QuantumXenon/origins-plus-plus#68] opened 2022-08-27 06:38 UTC
**Loader**
Forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version - Forge 43.1.1
- Origins Version - 1.19.2 1.5.0.6
- Origins++ Version 1.7
- Pehkui Version 3.4.1

Its my first time downloading this mod and as soon as i try to make a world it makes the world and all the files but it wont load into the world. All it says is invalid player data.
I have tried deleting the player data folder but nothing changes.
And as soon as it says Invalid Player Data and I press continue it takes me to multiplayer even though im trying to play singleplayer

**Comment by Tox-y** [comment] 2022-08-27 06:49
By the way I have downloaded the mod through CurseForge

**Comment by QuantumXenon** [comment] 2022-08-27 08:37
I had a similar issue. The fix I used was XL Packets for Forge (I know there isn’t a 1.19 version - I manually updated it myself). I have submitted the updated version to the GitHub page, so hopefully it will be available soon (https://github.com/Tfarcenim/XLPackets/pull/7)

**Comment by SubZeroAmber** [comment] 2022-08-27 21:19
@QuantumXenon would it be possible to have the updated jar file for this as it is causing multiplayer world to crash?

**Comment by QuantumXenon** [comment] 2022-08-27 21:52
@SubZeroAmber Here is the (unofficial) XL Packets 1.19 that I updated: https://github.com/QuantumXenon/xl-packets/releases/tag/1.19 - this won't distribute over CurseForge though so you will have to do it manually.

The reason it crashes is that my mod makes the data packets too big (because it adds many origins), so I can't fix it without removing some or by having another mod (like XL Packets)

**Comment by SubZeroAmber** [comment] 2022-08-27 22:06
@QuantumXenon I sincearly appreciate it! - It was horrible because as the server admin, i picked an origin class from the pluses one and i just crashed the entire server just by joining it. I sincearly appreciate this - i tested it just now and sadly - i am still crashing the entire server. I guess we will do without this mod for now.

**Comment by QuantumXenon** [comment] 2022-08-27 22:08
@SubZeroAmber Can you send a log?

**Comment by SubZeroAmber** [comment] 2022-08-27 22:11
I just noticed it is not locating the updated XL. jar file in the first place so this might as well be the cause - here is the log
[crash-2022-08-27_22.10.03-server.txt](https://github.com/QuantumXenon/origins-plus-plus/files/9438760/crash-2022-08-27_22.10.03-server.txt)

**Comment by QuantumXenon** [comment] 2022-08-27 22:12
@SubZeroAmber And what Origin were you trying to use?

**Comment by SubZeroAmber** [comment] 2022-08-27 22:14
origins-1.19-1.6.2.jar,  origins-plus-plus-1.7.jar

**Comment by QuantumXenon** [comment] 2022-08-27 22:22
@SubZeroAmber Which Origin crashed the server?

**Comment by SubZeroAmber** [comment] 2022-08-27 22:23
it started crashing after the origins-plus-plus, so i beleive due to the outdated xl mod, the server can't keep up with the origin-plus-plus and it just gives up on life

**Comment by QuantumXenon** [comment] 2022-08-27 22:24
Sorry, the mod I sent was for Forge - I got confused because the original issue was about Forge. As it's Fabric, see https://github.com/apace100/origins-fabric/issues/581 where it appears that custom origins crash in 1.19.1/1.19.2 because of a bug in the Origins mod.

**Comment by QuantumXenon** [comment] 2022-08-27 22:25
The XL packets for Fabric marked as 1.17/1.18 on CurseForge still works in 1.19 if you're still looking for that, but it won't help with the issue

**Comment by SubZeroAmber** [comment] 2022-08-27 22:28
I also forgot there were 2 versions... Ah well... so until origins is fixed for ver 1.19 and up, i might as well not bother with the mod?

**Comment by QuantumXenon** [comment] 2022-08-27 22:29
@SubZeroAmber Correct, it won't work with anything above 1.19 until the Origins mod is updated

**Comment by SubZeroAmber** [comment] 2022-08-27 22:30
Thank you so much for the assistance! I should of looked further into this, however as i am new to modpacks abnd everything ( i spend the entire day fighting with them) I do not understand a lot of things. I will share it with my players, so once again thank you for the help <3 :)

**Comment by QuantumXenon** [comment] 2022-08-27 22:32
@SubZeroAmber No problem. It isn't very clear that this issue exists for 1.19.1/1.19.2 unless you look at the issues for the Origins mod, so there are probably many people who have the same issue (and I did to).

**Comment by QuantumXenon** [comment] 2022-08-27 22:33
As for @Tox-y, you could still use https://github.com/QuantumXenon/xl-packets/releases/tag/1.19 to fix your issue, but again, it won't distribute over CurseForge until the author allows the pull request (if they do) and uploads a new version.

**Comment by Tox-y** [comment] 2022-08-27 23:39
Yeah I manually put the mod into the folders and it fixed the problem. Thank you for the help

**Closed** 2022-08-27 23:42 UTC
Labels: bug
