### ISSUE TITLE
Exception in Server Tick Loop

### ISSUE THREAD

**Issue by JustNossYT** [QuantumXenon/origins-plus-plus#61] opened 2022-08-14 21:53 UTC
**Version**
fabric

**Origin**
all

**Power**
all

**Notes**
the server just crashes

here r the crash logs

---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-08-14 22:47:12
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.lambda$action$0(AndAction.java:14)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.action(AndAction.java:14)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActiveCooldownPower.onUse(ActiveCooldownPower.java:32)
	at io.github.apace100.apoli.networking.ModPacketsC2S.lambda$useActivePowers$2(ModPacketsC2S.java:78)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 728917392 bytes (695 MiB) / 1380974592 bytes (1317 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 11
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21343.34
	Virtual memory used (MB): 18829.45
	Swap memory total (MB): 5018.66
	Swap memory used (MB): 536.19
	JVM Flags: 1 total; -Xmx2G
	Fabric Mods: 
		fabric-api: Fabric API 0.59.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.10+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.8+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.16+83a8659290
			fabric-command-api-v1: Fabric Command API (v1) 1.2.10+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.6+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.27+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.33+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.2+83a8659290
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.4+bd0a0d4a90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.7+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.29+a6d2f78590
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.17+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.27+9ff28f4090
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.27+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.20+1899036190
			fabric-item-api-v1: Fabric Item API (v1) 1.5.6+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.27+6bee109e90
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+83a8659290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.5+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.2+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.13+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.3+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.20+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.10+7675279690
			fabric-particles-v1: Fabric Particles (v1) 1.0.9+dc39553a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.23+23c4cfef90
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.13+9ff28f4090
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.6+9ff28f4090
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.10+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.0+6bee109e90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.12+9ff28f4090
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.10+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.2.0+1e232e1390
		fabricloader: Fabric Loader 0.14.9
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
				cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
				cloth-config: Cloth Config v6 7.0.65
					cloth-basic-math: cloth-basic-math 0.6.1
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		origins-plus-plus: Origins++ 1.6.2
		pehkui: Pehkui 3.4.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
	Server Running: true
	Player Count: 2 / 20; [class_3222['NossPlays'/222, l='ServerLevel[world]', x=-8.24, y=66.00, z=-2.75], class_3222['Sw34t0nSteds'/290, l='ServerLevel[world]', x=-6.48, y=66.00, z=-2.11]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by QuantumXenon** [comment] 2022-08-14 22:28
@JustNossYT Did you load into the world, or was this during server start-up?

**Comment by JustNossYT** [comment] 2022-08-14 22:29
loaded in

**Comment by JustNossYT** [comment] 2022-08-14 22:30
im on fabric
btw

**Comment by JustNossYT** [comment] 2022-08-14 22:30
it happens whenever i use a ability or chose my character

**Comment by QuantumXenon** [comment] 2022-08-14 22:33
Is it a specific ability or any ability?

**Comment by JustNossYT** [comment] 2022-08-14 22:33
Any

**Comment by JustNossYT** [comment] 2022-08-14 22:35
Is there anything I can do or do I just have to wait? My friends really wanna play on the server but it just ends up crashing

**Comment by JustNossYT** [comment] 2022-08-14 22:36
Like should I contact you on discord or smtn?

**Comment by QuantumXenon** [comment] 2022-08-14 22:36
I'm working on replicating the issue at the moment to see if I can figure out the cause

**Comment by QuantumXenon** [comment] 2022-08-14 22:39
I'm going to merge this issue and #55 because they are the same

**Comment by JustNossYT** [comment] 2022-08-14 22:40
K. Sorry to sound like a Karen but how long will this take?
Again, sorry for asking.

**Comment by QuantumXenon** [comment] 2022-08-14 22:41
I don't know. It looks like it could be an issue with the Origins mod itself though

**Comment by JustNossYT** [comment] 2022-08-14 22:41
OK. Thank you

**Comment by QuantumXenon** [comment] 2022-08-14 22:44
I think there is an issue with the Origins mod processing Origins++, which is causing an issue. You should be able to use the Origins mod on it own fine

**Comment by QuantumXenon** [comment] 2022-08-14 22:52
From the developer of Origins: 
https://github.com/apace100/origins-fabric/issues/581#issuecomment-1201637804

**Comment by QuantumXenon** [comment] 2022-08-14 22:53
@JustNossYT Closing this as it is an issue with Origins itself - this makes Origins++ incompatible with 1.19.1/1.19.2 until it is fixed.

**Closed by QuantumXenon** 2022-08-14 22:53 UTC
Labels: bug, under investigation
